[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automata-lib>=9.0.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
